### ISSUE TITLE
Site broken in Safari (tested on 13.1.1)

### ISSUE THREAD

**Issue by thinkingsand** [LeedsRaspJam/www#2]
Title says it all. The cards don't align properly, see photo attached.
![Screenshot 2020-07-03 at 03 11 43](https://user-images.githubusercontent.com/2265483/86424612-ed660500-bcda-11ea-9ac2-d1199d9e7a88.png)

**Comment by jamesatjaminit** [comment]
Do you think its worth moving themes?

**Comment by thinkingsand** [comment]
Nah, not just for safari support. The site is still functional just the positioning is messed up.

**Comment by thinkingsand** [comment]
https://github.com/sharu725/cards/issues/11 matches. I've tried that code snippet - it doesn't fix it.

**Comment by jamesatjaminit** [comment]
Okay, I checked it on other browsers as well on browserstack and its just safari so I think it'll have to do

**Comment by thinkingsand** [comment]
https://github.com/sharu725/cards/issues/11#issuecomment-653600957

**Comment by thinkingsand** [comment]
Fixed in 890a78f1196e74b4f280abbe01f3ef5fa257b971.
