### ISSUE TITLE
Navigation menu on mobile

### ISSUE THREAD

**Issue by jamesatjaminit** [LeedsRaspJam/www#3]
On mobile a menu icon appeared in the top right of the screen. When tapped it shows nothing but moves everything down a little. Is there any way to hide the menu or populate it with the links below?

**Comment by thinkingsand** [comment]
Fixed it but it's turned the text blue?

**Comment by jamesatjaminit** [comment]
I can't see anything in the code which would have caused that really

**Comment by jamesatjaminit** [comment]
What about just having ```<nav></nav>```

**Comment by thinkingsand** [comment]
Stop closing the issue until we've confirmed it's actually fixed.

**Comment by jamesatjaminit** [comment]
I'm not, it auto does it

**Comment by thinkingsand** [comment]
My apologies

**Comment by jamesatjaminit** [comment]
Thats worked, the grey is a bit too grey but at least its fixed

**Comment by jamesatjaminit** [comment]
Safe to close?

**Comment by thinkingsand** [comment]
No, that's way too light.

**Comment by jamesatjaminit** [comment]
Can't we just change the hex like you did originally?

**Comment by thinkingsand** [comment]
Yes but I want to know exactly what I'm changine. Don't want to mess something else up

**Comment by jamesatjaminit** [comment]
Fair enough, its black now

**Comment by thinkingsand** [comment]
There's still a tiny button there though. Give me a minute

**Comment by jamesatjaminit** [comment]
Okay, I think the button code that was added just needs removing to get rid of the border

**Comment by thinkingsand** [comment]
Then we'd be right back to the light grey

**Comment by jamesatjaminit** [comment]
What about changing the grey though, before it had `$grey_colour` couldn't you change that to a hex colour?

**Comment by jamesatjaminit** [comment]
This commit: https://github.com/LeedsRaspJam/www/pull/5/commits/30887fb54b78c91b7fdcd65f60bcf75a55602192

**Comment by thinkingsand** [comment]
What is the grey colour exactly, isn't that the light gray.

**Comment by jamesatjaminit** [comment]
That is the light grey, I was just meaning could we replace that with a hex value for a better colour

**Comment by thinkingsand** [comment]
No, don't modify existing code, makes intergrating updates far more difficult.

**Comment by jamesatjaminit** [comment]
We only need to change `$colour_grey` to `#433423something`

**Comment by jamesatjaminit** [comment]
The black looks fine though

**Comment by jamesatjaminit** [comment]
Fixed
